//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

		public class Level
		{

		private string orbName;	

			private string atmoName;
			
			private int levelIndex;
			
			public Level (string orbName, string levelName, int levelIndex)
			{
			this.orbName = orbName;
				this.atmoName = levelName;
				this.levelIndex = levelIndex;
			}
			
			public string AtmoName {
				get {
					return this.atmoName;
				}
				set {
					atmoName = value;
				}
			}
			
			public int LevelIndex {
				get {
					return this.levelIndex;
				}
				set {
					levelIndex = value;
				}
			}
		}

